eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: Sureshjuvva@876
    driver-class-name : com.mysql.cj.jdbc.Driver

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          ddl-auto: update
      show-sql: true